# Generated by Django 3.2.6 on 2021-09-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='nombre',
            new_name='ciudad',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='tipo',
        ),
    ]
